import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import loadLocalFont from "next/font/local";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";


const avenir = loadLocalFont({
  src: [
    {
      path: "../fonts/AvenirLTProRoman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/AvenirLTProMedium.otf",
      weight: "500",
      style: "normal",
    },
  ],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} ${avenir.className} antialiased`}>
        {children}
      </body>
      <Analytics />
    </html>
  );
}
